DEPOSIT = 1
WITHDRAWAL = 2
LOAN = 3
LOAN_PAID = 4
SEND_MONEY = 5
RECIVE_MONEY = 6
TRANSACTION_TYPE = (
    (DEPOSIT, 'Deposite'),
    (WITHDRAWAL, 'Withdrawal'),
    (LOAN, 'Loan'),
    (LOAN_PAID, 'Loan Paid'),
    (SEND_MONEY,'SEND_MONEY'),
    (RECIVE_MONEY,'RECIVE_MONEY'),
    
)